#!/usr/bin/env python
"""Write detector training labels from Dataset V1, one file per image.

Produces the YOLO layout a detector trainer expects -- ``labels/<split>/<name>.txt``
next to ``images/<split>/`` -- plus the dataset YAML the trainer is pointed at.
Images are **symlinked or listed, never copied**: 12,000 duplicated JPEGs would
be a second dataset to keep in sync, and the freeze already pins which files
belong to V1.

Each line is ``0 cx cy w h`` followed by the four plate corners as normalised
keypoints, in the order ``meta.csv`` stores them (clockwise from the plate's own
top-left). The class index is 0 for every row: the detector finds *plates*, and
the type is decided later by the recogniser, which sees the crop close up.

The real holdout is never exported. It is not training data and this script has
no flag that would make it so.

Usage::

    python scripts/export_detector_labels.py --out data/training/detector_v1
    python scripts/export_detector_labels.py --out <dir> --dry-run
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.training.data import DATASET, Sample, load_samples  # noqa: E402

#: Splits exported for detector training and validation. The real holdout is
#: absent by construction, and so is real:train -- baseline v1 fits on
#: synthetic only (see docs/baseline_v1.md).
EXPORTED_SPLITS: dict[str, str] = {
    "synthetic:train": "train",
    "synthetic:val": "val",
    "synthetic:test": "test",
}

EXIT_OK, EXIT_UNUSABLE = 0, 1


def _image_size(path: Path) -> tuple[int, int]:
    from PIL import Image

    with Image.open(path) as image:
        return image.size


def label_line(sample: Sample, width: int, height: int) -> str:
    """``0 cx cy w h  kx1 ky1 v1 ... kx4 ky4 v4``, all normalised to [0, 1]."""
    x, y, w, h = sample.bbox
    x1, y1 = max(0.0, x), max(0.0, y)
    x2, y2 = min(float(width), x + w), min(float(height), y + h)
    if x2 <= x1 or y2 <= y1:
        raise ValueError(f"{sample.image}: degenerate box after clipping to the image")
    parts = [
        "0",
        f"{(x1 + x2) / 2 / width:.6f}",
        f"{(y1 + y2) / 2 / height:.6f}",
        f"{(x2 - x1) / width:.6f}",
        f"{(y2 - y1) / height:.6f}",
    ]
    for kx, ky in sample.quad:
        # visibility 2 = labelled and visible; our corners always are, even when
        # the plate is occluded, because the corner position is still known.
        parts += [
            f"{min(max(kx / width, 0.0), 1.0):.6f}",
            f"{min(max(ky / height, 0.0), 1.0):.6f}",
            "2",
        ]
    return " ".join(parts)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "data" / "training" / "detector_v1")
    parser.add_argument("--dry-run", action="store_true", help="count and check, write nothing")
    args = parser.parse_args(argv)

    samples = [s for s in load_samples() if s.split in EXPORTED_SPLITS]
    if not samples:
        print("error: no samples; has the dataset been frozen?", file=sys.stderr)
        return EXIT_UNUSABLE

    by_image: dict[str, list[Sample]] = {}
    for sample in samples:
        by_image.setdefault(sample.image, []).append(sample)

    counts: Counter = Counter()
    written = 0
    for image, rows in sorted(by_image.items()):
        split = EXPORTED_SPLITS[rows[0].split]
        counts[split] += 1
        if args.dry_run:
            continue
        path = DATASET / image
        width, height = _image_size(path)
        lines = [label_line(row, width, height) for row in rows]
        label_path = args.out / "labels" / split / (Path(image).stem + ".txt")
        label_path.parent.mkdir(parents=True, exist_ok=True)
        label_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        written += 1

    if not args.dry_run:
        for split in sorted(set(EXPORTED_SPLITS.values())):
            listing = args.out / f"{split}.txt"
            listing.parent.mkdir(parents=True, exist_ok=True)
            listing.write_text(
                "\n".join(
                    str((DATASET / image).resolve())
                    for image, rows in sorted(by_image.items())
                    if EXPORTED_SPLITS[rows[0].split] == split
                )
                + "\n",
                encoding="utf-8",
            )
        (args.out / "dataset.yaml").write_text(
            "# Detector dataset for baseline v1. Generated by\n"
            "# scripts/export_detector_labels.py -- do not edit by hand.\n"
            "# Images are referenced in place; nothing is copied.\n"
            f"path: {args.out.resolve()}\n"
            "train: train.txt\n"
            "val: val.txt\n"
            "test: test.txt\n"
            "names:\n"
            "  0: plate\n"
            "kpt_shape: [4, 3]\n"
            "flip_idx: [1, 0, 3, 2]\n",
            encoding="utf-8",
        )
        (args.out / "export_record.json").write_text(
            json.dumps(
                {
                    "images": dict(counts),
                    "label_files": written,
                    "splits_exported": sorted(set(EXPORTED_SPLITS.values())),
                    "excluded": ["real:train", "real:val", "real:holdout"],
                    "note": "baseline v1 fits on synthetic only; real images are evaluation",
                },
                indent=1,
            )
            + "\n",
            encoding="utf-8",
        )

    print(f"images per split : {dict(counts)}")
    print(f"label files      : {written}{' (dry run)' if args.dry_run else ''}")
    print(f"output           : {args.out}")
    print("excluded         : real:train, real:val, real:holdout (never detector training data)")
    return EXIT_OK


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
